spring:
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url: jdbc:h2:file:/C:/Users/Radzi/IdeaProjects/ToDo/tododb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
  database-platform: org.hibernate.dialect.H2Dialect
task.allowMultipleTaskFromTemplate: true