spring:
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url: 'jdbc:h2:file:/C:/Users/Radzi/IdeaProjects/ToDo/tododb'
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
task.template.allowMultipleTaskFromTemplate: true
